In [1]:
import pandas as pd
import geopandas as gpd

In [6]:
conflict_grid = gpd.read_file('/Users/anfelipecb/Library/CloudStorage/Box-Box/MSCAPP/3rd Quarter/Machine Learning/Project/project-aeyzaguirre-phernandezpedraz-afcamachob/data/output/grid_conflict.geojson')

In [7]:
conflict_grid

,GEOID,year,conflict_count,geometry
0,1,2017,0,"POLYGON ((-17.17448 14.27993, -17.17448 14.730..."
1,1,2021,0,"POLYGON ((-17.17448 14.27993, -17.17448 14.730..."
2,1,1989,0,"POLYGON ((-17.17448 14.27993, -17.17448 14.730..."
3,1,1990,0,"POLYGON ((-17.17448 14.27993, -17.17448 14.730..."
4,1,1991,0,"POLYGON ((-17.17448 14.27993, -17.17448 14.730..."
...,...,...,...,...
456255,13036,1999,0,"POLYGON ((51.31069 11.57723, 51.31069 12.02768..."
456256,13036,2000,0,"POLYGON ((51.31069 11.57723, 51.31069 12.02768..."
456257,13036,2001,0,"POLYGON ((51.31069 11.57723, 51.31069 12.02768..."
456258,13036,2022,0,"POLYGON ((51.31069 11.57723, 51.31069 12.02768..."
456259,13036,2023,0,"POLYGON ((51.31069 11.57723, 51.31069 12.02768..."

In [8]:
conflict_grid.groupby('year').agg({'GEOID': 'nunique'}).rename(columns ={'GEOID': 'Num_GRIDS'})

      Num_GRIDS
year
1989      13036
1990      13036
1991      13036
1992      13036
1993      13036
1994      13036
1995      13036
1996      13036
1997      13036
1998      13036
1999      13036
2000      13036
2001      13036
2002      13036
2003      13036
2004      13036
2005      13036
2006      13036
2007      13036
2008      13036
2009      13036
2010      13036
2011      13036
2012      13036
2013      13036
2014      13036
2015      13036
2016      13036
2017      13036
2018      13036
2019      13036
2020      13036
2021      13036
2022      13036
2023      13036

In [19]:
#Read the final parquet
file_path = '/Users/anfelipecb/Library/CloudStorage/Box-Box/MSCAPP/3rd Quarter/Machine Learning/Project/project-aeyzaguirre-phernandezpedraz-afcamachob/data/output/grid_conflict_climate_2019_23.parquet'
final_gdf = pd.read_parquet(file_path)

In [20]:
final_gdf

,GEOID,year,conflict_count,temp_mean,temp_max,precip_total,sp_mean,rwi_2021,forest_loss,lights_mean,lights_sum,accumulated_conflicts,temp_deviation
1,1,2021,0,NaN,NaN,NaN,NaN,0.752576,0.0,0.307777,3.693320,0,NaN
14,1,2019,0,NaN,NaN,NaN,NaN,0.752576,0.0,0.160328,1.923936,1,NaN
15,1,2020,0,NaN,NaN,NaN,NaN,0.752576,0.0,0.245173,2.942070,1,NaN
16,1,2022,0,NaN,NaN,NaN,NaN,0.752576,0.0,0.288021,3.456250,1,NaN
17,1,2023,0,NaN,NaN,NaN,NaN,0.752576,0.0,0.343001,4.116006,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234631,13036,2021,0,298.931565,309.232956,0.079550,96319.055667,NaN,0.0,0.267979,3.215752,0,-0.263844
234644,13036,2019,0,299.477335,310.209900,0.240952,96638.664223,NaN,0.0,0.153874,1.846484,1,0.281926
234645,13036,2020,0,299.293418,309.668446,0.295275,96305.418242,NaN,0.0,0.241038,2.892451,1,0.098009
234646,13036,2022,0,299.093328,309.628448,0.158219,96282.639483,NaN,0.0,0.284016,3.408193,1,-0.102082
234647,13036,2023,0,299.447113,309.861099,0.172341,96353.797019,NaN,0.0,0.330492,3.965908,1,0.251703

In [10]:
final_gdf['conflict_count'].value_counts()

conflict_count
0      225112
1        4271
2        1703
3         867
4         590
        ...
96          1
95          1
126         1
81          1
167         1
Name: count, Length: 101, dtype: int64

In [11]:
final_gdf[final_gdf['year'] >=2019]['conflict_count'].describe()

count    65180.000000
mean         0.305063
std          2.920662
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        304.000000
Name: conflict_count, dtype: float64

In [14]:
final_gdf['year'].value_counts()

year
2017    13036
2021    13036
2022    13036
2020    13036
2019    13036
2018    13036
2015    13036
2007    13036
2016    13036
2014    13036
2013    13036
2012    13036
2011    13036
2010    13036
2009    13036
2008    13036
2006    13036
2023    13036
Name: count, dtype: int64

In [22]:
final_gdf[final_gdf['year'] >=2019]['accumulated_conflicts'].value_counts()

accumulated_conflicts
0      54987
1       3104
2       1372
3        825
4        601
       ...
179        1
169        1
118        1
106        1
159        1
Name: count, Length: 213, dtype: int64